### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by coffeverton** [McFoggy/TodoOnFire#7]
Hi, I just begun the set-up process, but I'm facing some issues with some npm dependencies.
Also, I found that I need to install the firebase-cli.

Before I do all that, I must ask: Does this project still works? Does someone else still uses it?

I really would like to use it, but I'm afraid to spend more time setting this up just to find that it does not work anymore...

**Comment by McFoggy** [comment]
Hello, I have leaved the company where we used Mattermost, but I would say that there is no reason for it not to work.
Mattermost API for the `slash commands`  should have stayed stable and deployment on firebase should still work so... go and tell us.
