### ISSUE TITLE
how to install this into mattermost?

### ISSUE THREAD

**Issue by gstlouisgit** [McFoggy/TodoOnFire#8]
hi 

does this work? It looks like you ca create tasks per channel?  

How can I install this into mattermost as a plugin?  I do not understand the install steps, however I know how to upload into mattermost as a plugin.

**Comment by McFoggy** [comment]
the instructions on the README explain how to deploy a backend/server on firebase ; then on your mattermost installation you create a slash command and register the installed server url.
